Repository PixelGuys/Cubyz, pull requests merged in 2025-04, with the labels that each got.

#1350 Show tool durability in icon
  src/gui/components/ItemSlot.zig
Labels: enhancement, ui/ux

#1349 Ruby ore + diamond texture tweaks
  assets/cubyz/blocks/cut_ruby_block.zig.zon
  assets/cubyz/blocks/ruby_block.zig.zon
  assets/cubyz/blocks/ruby_ore.zig.zon
  assets/cubyz/blocks/textures/cut_diamond_block_reflectivity.png
  assets/cubyz/blocks/textures/cut_ruby_block.png
  assets/cubyz/blocks/textures/cut_ruby_block_reflectivity.png
  assets/cubyz/blocks/textures/diamond_block.png
  assets/cubyz/blocks/textures/diamond_block_reflectivity.png
  assets/cubyz/blocks/textures/ruby_block.png
  assets/cubyz/blocks/textures/ruby_block_reflectivity.png
  assets/cubyz/blocks/textures/ruby_ore.png
  assets/cubyz/blocks/textures/ruby_ore_reflectivity.png
  assets/cubyz/items/diamond.zig.zon
  assets/cubyz/items/textures/diamond.png
  assets/cubyz/items/textures/ruby.png
  assets/cubyz/recipes/special_recipes.zig.zon
Labels: enhancement, graphics

#1354 New selection wand texture
  assets/cubyz/items/textures/selection_wand.png
Labels: enhancement, graphics, ui/ux

#1355 Update tool template textures
  assets/cubyz/tools/axe.png
  assets/cubyz/tools/axe_overlay.png
  assets/cubyz/tools/pickaxe.png
  assets/cubyz/tools/shover.png
Labels: enhancement, graphics, ui/ux

#1347 Make the crosshair transparent
  assets/cubyz/shaders/graphics/Image.fs
  src/gui/windows/crosshair.zig
Labels: enhancement, graphics, ui/ux

#1251 Directional drops
  src/Inventory.zig
  src/renderer.zig
  src/rotation.zig
  src/rotation/stairs.zig
Labels: enhancement, engine, ui/ux

#1310 Add ladder assets
  assets/cubyz/blocks/textures/ladder/baobab.png
  assets/cubyz/blocks/textures/ladder/birch.png
  assets/cubyz/blocks/textures/ladder/mahogany.png
  assets/cubyz/blocks/textures/ladder/oak.png
  assets/cubyz/blocks/textures/ladder/pine.png
  assets/cubyz/blocks/textures/ladder/willow.png
  assets/cubyz/items/textures/ladder/baobab.png
  assets/cubyz/items/textures/ladder/birch.png
  assets/cubyz/items/textures/ladder/mahogany.png
  assets/cubyz/items/textures/ladder/oak.png
  assets/cubyz/items/textures/ladder/pine.png
  assets/cubyz/items/textures/ladder/willow.png
Labels: graphics, content
